### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/movies/550/providers


### Transformers
GET http://localhost:8080/api/movies/1858/providers


###
GET http://localhost:8080/api/movies/id/550


###
GET http://localhost:8080/api/movies/name/transformers


###
GET http://localhost:8080/api/movies/name/Thor


###
GET http://localhost:8080/api/provider
Content-Type: */*

###
#GET http://localhost:8080/api/movies/1858/providers/filtered
#Authorization: Bearer {{$auth.token("")}}
#Content-Type: */*

###

GET http://localhost:8080/api/movies/trending/day
Content-Type: application/json

###
GET http://localhost:8080/api/users
Content-Type: application/json

###
POST  http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Alice"
}

###

PUT http://localhost:8080/api/movies/users/1/providers
Content-Type: application/json

{
  "toAdd": ["Netflix", "Amazon", "amazon", "Paramount Plus"],
  "toRemove": ["Disney+"]
}

###

PUT http://localhost:8080/api/movies/users/1/providers
Content-Type: application/json

{
"toAdd": ["Disney+"],
"toRemove": ["Netflix"]
}

### by user filtered

GET http://localhost:8080/api/movies/1858/1/providers/filtered/ByUserProvider
Content-Type: application/json


### security

GET http://localhost:8080/security

###user

GET http://localhost:8080/api/users/test
Content-Type: */*

### DEBUG

GET /http://localhost:8080/api/debug


