### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:8080/api/movies/550/providers
Authorization: Bearer <dein_jwt_token>

###

GET http://localhost:8080/api/movies/id/550
Authorization: Bearer <dein_jwt_token>

###

GET http://localhost:8080/api/movies/name/transformers
Authorization: Bearer <dein_jwt_token>